package org.brailleblaster.importers;

import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.ParserConfigurationException;

import javax.xml.transform.Transformer;
import javax.xml.transform.TransformerException;
import javax.xml.transform.TransformerFactory;
import javax.xml.transform.TransformerConfigurationException;
import javax.xml.transform.dom.DOMSource;
import javax.xml.transform.stream.StreamSource;
import javax.xml.transform.stream.StreamResult;
import java.io.*;
import org.w3c.dom.Document;
import org.xml.sax.SAXException;

import org.brailleblaster.localization.LocaleHandler;

public class XSLtransformer {
	
	public XSLtransformer () {
		
	}

	public boolean transformXml (String xsl, String fileName, String outFile) {

		Document document;
		
		try {
			DocumentBuilderFactory factory = DocumentBuilderFactory.newInstance();
			DocumentBuilder builder = factory.newDocumentBuilder();

			document = builder.parse(new File (fileName));
		
			File out = new File(outFile);
		StreamSource stylesource = new StreamSource(new File (xsl));
		TransformerFactory tFactory = TransformerFactory.newInstance();
		Transformer transformer = tFactory.newTransformer(stylesource);
		
		DOMSource source = new DOMSource(document);
        StreamResult result = new StreamResult(out);

        transformer.transform(source, result);
        
		} catch (TransformerConfigurationException tce) {
            // Error generated by the parser
            System.err.println("\n** Transformer Factory error");
            System.err.println("   " + tce.getMessage());

            // Use the contained exception, if any
            Throwable x = tce;

            if (tce.getException() != null) {
                x = tce.getException();
                x.printStackTrace();
            }

            return false;
            
        } catch (TransformerException te) {
            // Error generated by the parser
            System.out.println("\n** Transformation error");
            System.out.println("   " + te.getMessage());

            // Use the contained exception, if any
            Throwable x = te;

            if (te.getException() != null) {
                x = te.getException();
                x.printStackTrace();
            }

            return false;
            
        } catch (SAXException sxe) {
            // Error generated by this application
            // (or a parser-initialization error)
            Exception x = sxe;

            if (sxe.getException() != null) {
                x = sxe.getException();
                x.printStackTrace();
            }

            System.out.println("\n** Transformation error");
            System.out.println("   " + sxe.getMessage());

            return false;
            
        } catch (ParserConfigurationException pce) {
            // Parser with specified options can't be built
            System.out.println("\n** Transformation error");
            System.out.println("   " + pce.getMessage());

        	//pce.printStackTrace();
            return false;

        } catch (IOException ioe) {
            // I/O error
            System.out.println("\n** Transformation error");
            System.out.println("   " + ioe.getMessage());

            //ioe.printStackTrace();
            return false;
        }

		return true;
	}
}
