package org.brailleblaster.wordprocessor;

public enum BBEvent {
	INCREMENT,
	DECREMENT,
	TEXT_DELETION,
	UPDATE,
	REMOVE_NODE,
	SET_CURRENT,
	GET_CURRENT,
	GET_TEXT_MAP_ELEMENTS,
	ADJUST_ALIGNMENT,
	ADJUST_INDENT,
	UPDATE_STATUSBAR,
	UPDATE_CURSORS,
	ADJUST_RANGE;
}
